import java.io.RandomAccessFile;

public class StacjaPomiarowa extends java.applet.Applet {
        RandomAccessFile raf;
    long i1,i2,dl;
    long p;
    private String password = "PermitMe";
    
    //Tryb developerski, pokazuje hasło operatora w oknie "INFO..."
    final boolean dev_mode = true;
    final String rev = "1.1.4a";

    /**
     * Initializes the applet StacjaPomiarowa
     */
    public void init() {
        setSize(579, 447);
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                    try{
            raf = new RandomAccessFile("db.dat","rw"); //inicjacja RAF
            i1 = raf.getFilePointer(); //pobieramy pointer początku
            for(int i=0; i < 9; i++){
                raf.readUTF(); //MUSIMY odczytać tyle linii, ile jest pól, inaczej nie będzie się dało obliczać pointera
            }
            i2 = raf.getFilePointer(); //pobieramy pointer końca
            dl = i2 - i1; //pomocnicze
            p = i1;
         
        }catch(Exception e){
                status.setBackground(new java.awt.Color(249, 224, 224));
                status.setForeground(new java.awt.Color(190, 0, 0));
                status.setText("Błąd w RAF/init()! "+e);
        }
                    
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        data = new javax.swing.JTextField();
        temperatura = new javax.swing.JTextField();
        wilgotnosc = new javax.swing.JTextField();
        opad = new javax.swing.JTextField();
        opad_typ = new javax.swing.JComboBox<>();
        zamglenie = new javax.swing.JSlider();
        jLabel8 = new javax.swing.JLabel();
        zachmurzenie = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        wiatr = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cisnienie = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        prev = new javax.swing.JButton();
        next = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();
        jLabel20 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        status = new javax.swing.JTextField();
        toggleInfo = new javax.swing.JButton();

        jDialog1.setTitle("Informacje dodatkowe");
        jDialog1.setSize(420,264);
        jDialog1.setIconImage(null);
        jDialog1.setIconImages(null);
        jDialog1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("INFORMACJE DODATKOWE");
        jDialog1.getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 400, 30));

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Program na zaliczenie z przedmiotu Języki Programowania");
        jDialog1.getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 44, 400, 20));

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("Semestr zimowy, rok 2017/2018");
        jDialog1.getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 400, -1));

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setText("Prowadzący ćwiczenia: dr inż. Wojciech Froelich");
        jDialog1.getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 400, 20));

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        if(dev_mode == true) {
            jLabel27.setText("Hasło operatora do celów testowych: ");
        } else {jLabel27.setText("Build: ");}
        jDialog1.getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 230, 20));

        jLabel28.setText("Ⓒ 2018 by Michał Michalski, I inż D7");
        jDialog1.getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 80, -1));

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 0, 0));
        if(dev_mode == true) {
            jTextField1.setText(password);
        } else {jTextField1.setText("v "+rev);}
        jDialog1.getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 150, 20));

        jDialog1.getAccessibleContext().setAccessibleName("INFO / copyright");

        setBackground(new java.awt.Color(248, 248, 248));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("Fikcyjna Stacja Pomiarowa e-Prognoza"); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(4, 1, 113));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("» Fikcyjny punkt pomiarowy ePogoda");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 579, -1));

        jLabel2.setText("Data [d/m/y]:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jLabel3.setText("Temperatura [℃]:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel4.setText("Wilgotność [%]:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel5.setText("Opad [mm]:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jLabel6.setText("Typ opadu:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel7.setText("Zamglenie [0-5]:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        data.setToolTipText("Wprowadź datę w schemacie dd/mm/yyyy");
        data.setNextFocusableComponent(temperatura);
        add(data, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 50, 150, 30));

        temperatura.setToolTipText("Wprowadź wartość w stopniach Celsjusza");
        temperatura.setNextFocusableComponent(wilgotnosc);
        add(temperatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 150, 30));

        wilgotnosc.setToolTipText("Wprowadź procentową wartość wilgotności powietrza");
        wilgotnosc.setNextFocusableComponent(opad);
        add(wilgotnosc, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 150, 30));

        opad.setToolTipText("Wprowadź wartość opadu deszczu w milimetrach");
        opad.setNextFocusableComponent(opad_typ);
        add(opad, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 150, 30));

        opad_typ.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Brak", "Deszcz", "Snieg", "Mieszany" }));
        opad_typ.setToolTipText("Wybierz typ opadu.");
        add(opad_typ, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 150, 30));

        zamglenie.setMajorTickSpacing(1);
        zamglenie.setMaximum(5);
        zamglenie.setMinorTickSpacing(1);
        zamglenie.setPaintLabels(true);
        zamglenie.setPaintTicks(true);
        zamglenie.setSnapToTicks(true);
        zamglenie.setToolTipText("Określ stopień zamglenia. 0 - brak; 5 - bardzo duże.");
        zamglenie.setValue(0);
        zamglenie.setNextFocusableComponent(zachmurzenie);
        add(zamglenie, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 150, 40));

        jLabel8.setText("Zachmurzenie:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        zachmurzenie.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Brak", "Lekkie", "Czesciowe", "Srednie", "Duze", "Pelne" }));
        zachmurzenie.setToolTipText("Wybierz rodzaj zachmurzenia");
        add(zachmurzenie, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 150, 30));

        jLabel9.setText("Wiatr [m/s]:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        wiatr.setToolTipText("Podaj siłę wiatru w m/s.");
        wiatr.setNextFocusableComponent(cisnienie);
        add(wiatr, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 150, 30));

        jLabel10.setText("Ciśnienie [hPa]:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        cisnienie.setToolTipText("Podaj ciśnienie powietrza w hektopascalach.");
        cisnienie.setNextFocusableComponent(pass);
        add(cisnienie, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 150, 30));

        jLabel12.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 255));
        jLabel12.setText("[ ? ]");
        jLabel12.setToolTipText("Wprowadź datę w schemacie dd/mm/yyyy. Przykład: 23/07/1997");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 20, 30));

        jLabel13.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 255));
        jLabel13.setText("[ ? ]");
        jLabel13.setToolTipText("Wprowadź temperaturę w *C. Przykład: 25 lub -08");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 30, 30));

        jLabel11.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 255));
        jLabel11.setText("[ ? ]");
        jLabel11.setToolTipText("Wprowadź procentową wilgotność powietrza. Przykład: 65");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, -1, 30));

        jLabel14.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 255));
        jLabel14.setText("[ ? ]");
        jLabel14.setToolTipText("Wprowadź opad w milimetrach. Przykład: 21");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, 30));

        jLabel15.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 255));
        jLabel15.setText("[ ? ]");
        jLabel15.setToolTipText("Wybierz typ opadu z listy.");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, -1, 30));

        jLabel16.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 255));
        jLabel16.setText("[ ? ]");
        jLabel16.setToolTipText("Wybierz stopień zamglenia [0-5]. 0 - brak zamglenia, 5 - maksymalne zamglenie.");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, 40));

        jLabel17.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 255));
        jLabel17.setText("[ ? ]");
        jLabel17.setToolTipText("Wybierz stopień zachmurzenia.");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, -1, 30));

        jLabel18.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 255));
        jLabel18.setText("[ ? ]");
        jLabel18.setToolTipText("Podaj prędkość wiatru w metrach na sekundę. Przykład: 12");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, -1, 30));

        jLabel19.setFont(new java.awt.Font("Cambria", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 255));
        jLabel19.setText("[ ? ]");
        jLabel19.setToolTipText("Podaj ciśnienie w hektopaskalach. Przykład: 1012");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, -1, 30));

        add.setBackground(new java.awt.Color(204, 255, 204));
        add.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        add.setForeground(new java.awt.Color(0, 204, 0));
        add.setText("+");
        add.setToolTipText("Umożliwia zapisanie pomiaru, po wprowadzeniu hasła operatora.");
        add.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        add.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 190, 60));

        clear.setBackground(new java.awt.Color(255, 204, 204));
        clear.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        clear.setForeground(new java.awt.Color(255, 0, 0));
        clear.setText("X");
        clear.setToolTipText("Czyści formularz");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 130, 190, 60));

        prev.setBackground(new java.awt.Color(204, 204, 255));
        prev.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        prev.setForeground(new java.awt.Color(51, 51, 255));
        prev.setText("«");
        prev.setToolTipText("Ładuje do pól starsze wpisy");
        prev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prevActionPerformed(evt);
            }
        });
        add(prev, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 80, 170));

        next.setBackground(new java.awt.Color(204, 204, 255));
        next.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        next.setForeground(new java.awt.Color(51, 51, 255));
        next.setText("»");
        next.setToolTipText("Ładuje do pól nowsze wpisy");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 80, 170));

        pass.setBackground(new java.awt.Color(255, 153, 153));
        pass.setForeground(new java.awt.Color(255, 255, 255));
        pass.setToolTipText("Wprowadź hasło operatora, aby dodać wpis");
        pass.setNextFocusableComponent(add);
        add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 110, -1));

        jLabel20.setText("Operator:");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, 20));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 190, 10));

        jLabel21.setBackground(new java.awt.Color(255, 204, 204));
        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setText("[ ? ]");
        jLabel21.setToolTipText("Wpisy mogą dodawać jedynie operatorzy, po wpisaniu odpowiedniego hasła.");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 30, 20));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Status»");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, -1, 20));

        status.setEditable(false);
        status.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        status.setForeground(new java.awt.Color(102, 102, 102));
        status.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        status.setText("Gotowy do pracy");
        add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 420, 410, -1));

        toggleInfo.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        toggleInfo.setText("INFO...");
        toggleInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleInfoActionPerformed(evt);
            }
        });
        add(toggleInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 420, 90, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        try{
            if((data.getText().matches("[0-9]{2}/[0-9]{2}/[0-9]{4}"))
                && (temperatura.getText().matches("-?[0-9]{1,2}"))
                && (wilgotnosc.getText().matches("[0-9]{1,3}"))
                && (opad.getText().matches("[0-9]{1,3}"))
                && (wiatr.getText().matches("[0-9]{1,2}"))
                && (cisnienie.getText().matches("[0-9]{3,4}"))) {
                        if(pass.getText().equals(password)){
                            try {
                                raf.seek(raf.length());
                                raf.writeUTF(data.getText());
                                raf.writeUTF(temperatura.getText());
                                raf.writeUTF(wilgotnosc.getText());
                                raf.writeUTF(opad.getText());
                                raf.writeUTF(String.valueOf(opad_typ.getSelectedItem()));
                                raf.writeUTF(String.valueOf(zamglenie.getValue()));
                                raf.writeUTF(String.valueOf(zachmurzenie.getSelectedItem()));
                                raf.writeUTF(wiatr.getText());
                                raf.writeUTF(cisnienie.getText());
                            status.setBackground(new java.awt.Color(204,255,204));
                            status.setForeground(new java.awt.Color(10, 155, 7));
                            status.setText("Dane zapisane poprawnie!");
                            }catch(Exception e){
                            status.setBackground(new java.awt.Color(249, 224, 224));
                            status.setForeground(new java.awt.Color(190, 0, 0));
                            status.setText("Błąd zapisu do pliku! "+e);
                            }
                        } else {
                            status.setBackground(new java.awt.Color(249, 224, 224));
                            status.setForeground(new java.awt.Color(190, 0, 0));
                            status.setText("Odmowa dostępu! Błędne hasło operatora.");
                        }
                        
            } else {
                status.setBackground(new java.awt.Color(249, 224, 224));
                status.setForeground(new java.awt.Color(190, 0, 0));
                status.setText("Błędne dane lub brak danych! Po pomoc najedź na [?] obok pola.");
            }
            
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_addActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        try{
            status.setBackground(new java.awt.Color(175, 219, 247));
            status.setForeground(new java.awt.Color(59, 65, 247));
            status.setText("Wyczyszczono pola formularza.");
            data.setText("");
            temperatura.setText("");
            wilgotnosc.setText("");
            opad.setText("");
            opad_typ.setSelectedItem("Brak");
            zamglenie.setValue(0);
            zachmurzenie.setSelectedItem("Brak");
            wiatr.setText("");
            cisnienie.setText("");
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_clearActionPerformed

    private void prevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prevActionPerformed
        try{
            p = p - dl;
            status.setBackground(new java.awt.Color(175, 219, 247));
            status.setForeground(new java.awt.Color(59, 65, 247));
            status.setText("Załadowano starszy wpis.");
            if(p == 0){//jeśli pointer jest już na zerze to błąd
                status.setBackground(new java.awt.Color(249, 224, 224));
                status.setForeground(new java.awt.Color(190, 0, 0));
                status.setText("Nie znaleziono starszych wpisów.");
            }
            raf.seek(p);
            data.setText(raf.readUTF());
            temperatura.setText(raf.readUTF());
            wilgotnosc.setText(raf.readUTF());
            opad.setText(raf.readUTF());
            opad_typ.setSelectedItem(raf.readUTF());
            zamglenie.setValue(Integer.parseInt(raf.readUTF()));
            zachmurzenie.setSelectedItem(raf.readUTF());
            wiatr.setText(raf.readUTF());
            cisnienie.setText(raf.readUTF());
                
           /* data.setText("");
            temperatura.setText("");
            wilgotnosc.setText("");
            opad.setText("");
            opad_typ.setSelectedItem("Brak");
            zamglenie.setValue(0);
            zachmurzenie.setSelectedItem("Brak");
            wiatr.setText("");
            cisnienie.setText(""); */
        }catch(Exception e){
                status.setBackground(new java.awt.Color(249, 224, 224));
                status.setForeground(new java.awt.Color(190, 0, 0));
                status.setText("Nie znaleziono starszych wpisów.");
        }
    }//GEN-LAST:event_prevActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        try{
            data.setText(raf.readUTF());
            temperatura.setText(raf.readUTF());
            wilgotnosc.setText(raf.readUTF());
            opad.setText(raf.readUTF());
            opad_typ.setSelectedItem(raf.readUTF());
            zamglenie.setValue(Integer.parseInt(raf.readUTF()));
            zachmurzenie.setSelectedItem(raf.readUTF());
            wiatr.setText(raf.readUTF());
            cisnienie.setText(raf.readUTF());
            p = p + dl;
            status.setBackground(new java.awt.Color(175, 219, 247));
            status.setForeground(new java.awt.Color(59, 65, 247));
            status.setText("Załadowano nowszy wpis.");
           /* data.setText("");
            temperatura.setText("");
            wilgotnosc.setText("");
            opad.setText("");
            opad_typ.setSelectedItem("Brak");
            zamglenie.setValue(0);
            zachmurzenie.setSelectedItem("Brak");
            wiatr.setText("");
            cisnienie.setText(""); */
        }catch(Exception e){
                status.setBackground(new java.awt.Color(249, 224, 224));
                status.setForeground(new java.awt.Color(190, 0, 0));
                status.setText("Nie znaleziono nowszych wpisów.");           
        }
    }//GEN-LAST:event_nextActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jDialog1.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void toggleInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleInfoActionPerformed
        jDialog1.setVisible(true);
    }//GEN-LAST:event_toggleInfoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField cisnienie;
    private javax.swing.JButton clear;
    private javax.swing.JTextField data;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton next;
    private javax.swing.JTextField opad;
    private javax.swing.JComboBox<String> opad_typ;
    private javax.swing.JPasswordField pass;
    private javax.swing.JButton prev;
    private javax.swing.JTextField status;
    private javax.swing.JTextField temperatura;
    private javax.swing.JButton toggleInfo;
    private javax.swing.JTextField wiatr;
    private javax.swing.JTextField wilgotnosc;
    private javax.swing.JComboBox<String> zachmurzenie;
    private javax.swing.JSlider zamglenie;
    // End of variables declaration//GEN-END:variables
}
